### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by mambax7** [shin1x1/domain-modeling-with-php#2]
Any chance to have the presentation translated into English? 
Thanks!

**Comment by shin1x1** [comment]
Thank you for your interest in my presentation!
I'll try to find some time to do it.

**Comment by mambax7** [comment]
Thank you!

**Comment by shin1x1** [comment]
@mambax7 I translated the presentation and sample code. Please check it out!

* presentation
https://speakerdeck.com/shin1x1/domain-modeling-with-php-en

* sample code
https://github.com/shin1x1/domain-modeling-with-php/tree/main/en

**Comment by mambax7** [comment]
Awesome!!! Thank you so much!!!
